config/routes.rb
Rails.application.routes.draw do
  resources :students, except: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/student.rb
class Student < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :make_header, :make_link

  def make_header(title)
    "<h1>#{title}</h1>".html_safe
  end

  def make_link(text, path)
    if !path.is_a? String
      "<a href='/#{path.class.to_s.downcase.pluralize}/#{path.id}'>#{text}</a>".html_safe
    else
     "<a href='#{path}'>#{text}</a>".html_safe
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    # {student: {name: 'whatever', dob: ''}}
    Student.new(student_params)

    redirect_to students_path
  end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update
    @student = Student.find_by(id: params[:id])
    @student.update(student_params)

    redirect_to @student
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for(@student) do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :email %>
  <%= f.date_field :dob %>
  <%= f.submit%>
<% end %>

app/views/students/index.html.erb
<%= make_header('All the Students') %>

<ul>
  <% @students.each do |student| %>
    <li><%= make_link(student.name, student) %></li>
  <% end %>
</ul>

<%= make_link('Create a new student', new_student_path) %>

app/views/students/new.html.erb
<h1>Create a New Student</h1>

<%= form_tag('/students') do %>
  <%= text_field_tag :name %>
  <%= submit_tag 'Create a Student' %>
<% end %>

<%= link_to 'See all students', students_path %>

app/views/students/show.html.erb
<h1>Student Show</h1>

<h2><%= @student.name %></h2>
<h4><%= @student.email %></h4>

<%= link_to 'Back', '/students' %>
<%= link_to 'Edit this student', edit_student_path(@student)%>